# Site settings Update for my Blog : spaceg.github.io Do.9.April 15.49:24 2015 
title: Karol.Lacerda
email: karolfiel@live.com
description: "Hello, My Name is Karol Lacerda, I'm a Front End Engineer and Web Developer from Switzerland. This is my Personal Notice and Archive Work Experience Work Blog. My Official Website will be Up soon! Code and Space!"
baseurl: ""
url: "http://karollacerda16.github.com"
twitter_username: 
github_username:  karollacerda16
google_username:  https://plus.google.com/101826267816845608605/posts
instagram_username:  karollaf


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

paginate: 5 #posts per page

